services:
  - type: web
    name: wk-poule-api
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        sync: false
